pipeline {

    agent any
    environment {
        PASS = credentials('DOCKER_PASS') 
        UBUNTU_PASS = credentials('UBUNTUNO_PASS') 
    }

    stages {
        stage('Build') {
            steps {
                sh './jenkins/build/mvn.sh'
            }
            post {
                success {
                   archiveArtifacts artifacts: 'java-app/target/*.jar', fingerprint: true
                }
            }
        }
        
        stage('Test') {
            steps {
                sh './jenkins/test/mvn.sh'
            }
            post {
                always {
                    junit 'java-app/target/surefire-reports/*.xml'
                }
            }
        }

	stage('Push') {
            steps {
                sh './jenkins/push/mvn.sh'
            }
        }

	stage('Deploy') {
            steps {
                sh './jenkins/deploy/mvn.sh'
            }
        }
        
    }

}
